# Generated by Django 4.2 on 2024-02-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='secret_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
