# Generated by Django 4.2 on 2024-02-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quiz_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgrade',
            name='pass_status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Draw', 'Draw')], default='Draw', max_length=10),
        ),
    ]
