# Generated by Django 4.2 on 2024-02-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_quizgrade_pass_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgrade',
            name='pass_status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=10),
        ),
    ]
